
-- create
CREATE TABLE GROUPMATES (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO GROUPMATES VALUES (1, 'Mark', 25, 'Moscow');
INSERT INTO GROUPMATES VALUES (2, 'Rosa', 35, 'Saratov');
INSERT INTO GROUPMATES VALUES (3, 'Mark', 22, 'Bryansk');
INSERT INTO GROUPMATES VALUES (4, 'Natalya', 28, 'Moscow');
INSERT INTO GROUPMATES VALUES (5, 'Maks', 36, 'Ryasan');
INSERT INTO GROUPMATES VALUES (6, 'Venus', 20, 'Moscow');
INSERT INTO GROUPMATES VALUES (7, 'Sergey', 22, 'Moscow');
INSERT INTO GROUPMATES VALUES (8, 'Eva', 30, 'Moscow');
INSERT INTO GROUPMATES VALUES (9, 'Omega', 25, 'Orel');
INSERT INTO GROUPMATES VALUES (10, 'Oksana', 25, 'Moscow');

-- fetch
SELECT name AS 'Имя' 
FROM GROUPMATES 
WHERE adress = 'Moscow' AND age BETWEEN 18 AND 29